# based on https://github.com/pcolby/aws-sdk-qt/blob/master/.travis.yml

language: cpp

os:
  - linux

dist: bionic

compiler:
  - gcc

env:
  global:
  matrix:
    - QT=510 BREW=@ex PPA=beineri/opt-qt-5.11.1-bionic

addons:
  coverity_scan:
    project:
      name: "chili-epfl/qml-ar"
      description: "Build submitted via Travis CI"
    notification_email: sergei.volodin@epfl.ch
    build_command_prepend: >
      cp -a "$TRAVIS_BUILD_DIR" "$TRAVIS_BUILD_DIR-scan" &&
      pushd "$TRAVIS_BUILD_DIR-scan" &&
      qmake -qt=qt5 -Wall -Wlogic -Wparser CONFIG+=debug_and_release
    build_command: make -j10 all
    branch_pattern: coverity

before_install:
  - '[[ "$TRAVIS_OS_NAME" != linux || -z "$PPA" ]] || sudo add-apt-repository -y ppa:$PPA'
  - '[ "$TRAVIS_OS_NAME" != linux ] || sudo apt-get -qy update'

install:
#  - '[ "$TRAVIS_OS_NAME" != linux ] || sudo apt-get -qy install '
  - '[[ "$TRAVIS_OS_NAME" != linux || "$PPA" != */opt-* ]] || sudo apt-get -qy install qt${QT}base qt${QT}xmlpatterns libopencv-dev python3-opencv'
  - '[[ "$TRAVIS_OS_NAME" != linux || "$PPA" == */opt-* ]] || sudo apt-get -qy install qt5-qmake qtbase5-dev libqt5xmlpatterns5-dev'
  - qmake -v

before_script:
  - '[[ "$TRAVIS_OS_NAME" != linux || "$CXX" != g++     ]] || export QMAKESPEC=linux-g++'
  - '[[ "$TRAVIS_OS_NAME" != linux || "$PPA" != */opt-* ]] || . /opt/qt$QT/bin/qt$QT-env.sh'
  - '[[ "$TRAVIS_OS_NAME" != linux || "$PPA" == */opt-* ]] || export QT_SELECT=qt5'
  - mkdir -p "$TRAVIS_BUILD_DIR-build"
  - qmake -o "$TRAVIS_BUILD_DIR-build" -r -Wall -Wlogic -Wparser CONFIG+=debug_and_release "$TRAVIS_BUILD_DIR"

script:
  - make -j10 -C "$TRAVIS_BUILD_DIR-build" all
